# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pokedex-by-Ponyy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pokedex-by-Ponyy
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 5.0'

  target 'Pokedex-by-PonyyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pokedex-by-PonyyUITests' do
    # Pods for testing
  end

end
